---

# GitHub actions variables

project:
  - name: docker-actions-builder
  - branch: master
  - description: "Docker image used to develop build logic for templating GitHub actions."

release:
  - version: major
  - type: os
  - tag: latest
  
github_actions_params:
  - container_name: actions-builder
  - dockerhub_image_name: 'packershift/actions-builder'
