name: CI Workflow

on:
  push:
    branches:
       - develop

env:
  MULTI_ARCH: 'True'
  CONTAINER_NAME: 'actions-builder'
  DOCKERHUB_IMAGE_NAME: 'packershift/actions-builder'
  ORGANIZATION: 'packershift'
  PROJECT_REPO: 'docker-actions-builder'

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setting up environmental variables
        run: env