name: CI Workflow

on:
  push:
    branches:
       - develop

env:
  MULTI_ARCH: 'True'
  CONTAINER_NAME: 'actions-builder'
  DOCKERHUB_IMAGE_NAME: 'packershift/actions-builder'

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setting up env variables
        run: |
          echo DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z') >> $GITHUB_ENV
          echo COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV
    
      - name: Fetching up env varibales
        run: |
          echo MyDate=${{ env.DATE }}
          echo MYENv=${{ env.CONTAINER_NAME }}
          echo SHA=${{ env.COMMIT_SHA }}
          
