name: CI Workflow

on:
  push:
    branches:
       - develop

env:
  MULTI_ARCH: 'True'
  CONTAINER_NAME: 'actions-builder'
  DOCKERHUB_IMAGE_NAME: 'packershift/actions-builder'
  ORGANIZATION: 'packershift'
  PROJECT_REPO: 'docker-actions-builder'

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setting up environmental variables
        run: |
          echo EXIT_STATUS = '' >> $GITHUB_ENV
          echo PACKER_RELEASE=`docker run --rm ghcr.io/linuxserver/alexeiled-skopeo sh -c 'skopeo inspect docker://docker.io/'${{ env.DOCKERHUB_IMAGE_NAME }}':latest 2>/dev/null' | jq -r '.Labels.build_version' | awk '{print $3}' | grep '\\-ls' || :` >> $GITHUB_ENV
          echo PACKER_RELEASE_NOTES=`cat buildspec-readme.yml | awk -F \\" '/date: "[0-9][0-9].[0-9][0-9].[0-9][0-9]:/ {print $4;exit;}' | sed -E ':a;N;$!ba;s/\\r{0,1}\\n/\\\\n/g'` >> $GITHUB_ENV